### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by rosank** [aws-samples/amazon-gamelift-unity#12]
Hello, 
Sorry for the silly question, but after cloning the project I'm getting error. 
`The type or namespace name 'Amazon' could not be found (are you missing a using directive or an assembly reference?)
`
I'm using Unity 2018.4.23f, Do I have import AWS SDK packages. Also, I'm trying to build for Android. Gamelift support Android builds?

**Comment by alanmur** [comment]
Hello Rosank,
You should execute build.bat in the build folder to download the SDK, build it and put it in the Plugins folder. All should be good at that point. If you already did this, can you supply the output from this batch file, so that I can see what went wrong. Thank you!!!

**Comment by rosank** [comment]
Thank you It worked. I'm closing the issue
