### ISSUE TITLE
"Error occurred. Message:'The specified location-constraint is not valid' when writing an object"

### ISSUE THREAD

**Issue by herpdederp** [aws-samples/amazon-gamelift-unity#4]
#2 "Error creating a build bucket has been fixed."
However I am still getting the issue.

**Comment by alanmur** [comment]
Hello @herpdederp 
I couldn't repro this with a fresh clone of the project.
Can you run the batch file clean.bat in the build folder to make sure that there isn't an old DeployTool binary being used. If it still doesn't work, can you blow away the project, clone it again, then build it from the beginning (using build.bat)?
Thank you,
Al Murray :)

**Comment by alanmur** [comment]
Hello @herpdederp
I am going to close this issue. Please reopen if you have further issues.
Thank you,
Al Murray :)
