### ISSUE TITLE
Problem when trying to connect as a client to Gamelift.

### ISSUE THREAD

**Issue by xavinux** [aws-samples/amazon-gamelift-unity#8]
Hi,

I'm new to Gamelift, trying to make this game run to learn more about Game Tech on AWS.

I was able to build the code and deploy a fleet, but when running the rc.bat command with the alias flag and the alias name, Unity start and connect to a local server with 0 connections.

I'm running Windows 10 (64 bits) and have same problem with Unity versions 2017.4.36f1 LTS and the last version 2019.3.1f1, both installed through the Unity Hub version 2.2.2

Have attached some screenshots that maybe can be useful.

Thank you very much for your attention and sorry for the inconvenience.

Best Regards

![screen1](https://user-images.githubusercontent.com/4923082/74599643-0770b500-5064-11ea-9ca7-77daba720032.png)

![screen2](https://user-images.githubusercontent.com/4923082/74599644-0b043c00-5064-11ea-920e-02002af64c94.png)

![screen3](https://user-images.githubusercontent.com/4923082/74599648-122b4a00-5064-11ea-8dda-93b2e44b663c.png)

![screen4](https://user-images.githubusercontent.com/4923082/74599652-1a838500-5064-11ea-8e51-e8fde46bf93a.png)

**Comment by alanmur** [comment]
Hi!

What is in the log file at ```C:\Users\Javier\AppData\LocalLow\DefaultCompany\GameLiftUnity\output_log.txt```? It will help with information about why it didn't connect. I have to say that it is weird that your screenshot shows a server.

Another possible problem, is that the alias ID that you type into the command window (ending in ```22596f```) doesn't seem to exist in the dashboard screenshot, where you only have an alias ending in ```32c329```. Did you delete the alias that was created?

Thank you,
Al Murray

**Comment by xavinux** [comment]
Hi Al,

Thank you very much for your time to answer. Seems that I've uploaded the wrong screenshot. As you can see in the new one, have run the rc command with the same alias ID shown in the GameLift console.

Have also attached the output_log dile.

Best Regards.

[output_log.txt](https://github.com/aws-samples/amazon-gamelift-unity/files/4216672/output_log.txt)

![gamelift](https://user-images.githubusercontent.com/4923082/74692041-343bde00-51c4-11ea-920f-1dfd8a805be4.png)

![cli](https://user-images.githubusercontent.com/4923082/74692051-3d2caf80-51c4-11ea-8d1e-7faac51974e3.png)

**Comment by alanmur** [comment]
Hi!

You are getting an exception [on one of these lines](https://github.com/aws-samples/amazon-gamelift-unity/blob/master/Assets/Scripts/GameLift.cs#L392-L398). This probably indicates that the client doesn't have the credentials needed.

This might be a doc bug, actually.

Run through the steps [Creating a credentials file](https://github.com/aws-samples/amazon-gamelift-unity#creating-a-credentials-file), then [Installing a credentials file](https://github.com/aws-samples/amazon-gamelift-unity#installing-a-credentials-file). This should be a one-time operation.

Let me know if that works, and if so, I will make a fix to the project so nobody else hits this.

Thank you,
Al Murray :)

**Comment by xavinux** [comment]
HI Al,

I've done all the process one more time, build the SDK, the project, install the libraries, build the Client and Server, create the new policy and attached it to a new user and downloaded the CSV file. Move that file into the Build folder and after the Fleet was active, try to connect running the rc --credentials credentials.csv command, and still getting a local server running and can't connect to the GameLift fleet.

Have attached the output_log file.

Thank you again for your kind attention.

Best Regards.

[output_log.txt](https://github.com/aws-samples/amazon-gamelift-unity/files/4217025/output_log.txt)

**Comment by alanmur** [comment]
Hi!

I looked into this again today, but without much luck. I made a code project to try to reproduce the problem in my environment. It works on my machine. It runs exactly the code that fails on your machine with extra debug info. 
[ReproAuthFail.zip](https://github.com/aws-samples/amazon-gamelift-unity/files/4223042/ReproAuthFail.zip)
Can you get it, unzip it, open the ReproAuthFail.sln file in Visual Studio by double clicking it. Once it's loaded, press F5 to build and run it (Debug configuration). Please send any output you get from the program (a console window will pop up, a screenshot of that) or anything that happens in the Output window may be helpful. I'll look at what you send me.

I apologize for the difficulty you are seeing. Hopefully we will get you going again, as soon as I can figure out what went wrong for you.

Thank you,
Al :)

**Comment by xavinux** [comment]
Hi Al,

Nothing to excuse, I always learn a lot from the difficulties, rather than the successes ;)

I've build and run the ReproAuthFail.sln file in Visual Studio 2017. have attached the screenshots of the output errors.

Thanks again for your attention.

Best Regards

![error](https://user-images.githubusercontent.com/4923082/74872446-fbbf1000-533b-11ea-8288-1e1e54d3df7b.png)

![error_2](https://user-images.githubusercontent.com/4923082/74872448-fcf03d00-533b-11ea-9e99-86b191cf4385.png)

![error_3](https://user-images.githubusercontent.com/4923082/74872450-fd88d380-533b-11ea-976c-453af166ff6d.png)

![error_4](https://user-images.githubusercontent.com/4923082/74872452-fe216a00-533b-11ea-8adf-b4e2777fb570.png)

![error_5](https://user-images.githubusercontent.com/4923082/74872454-feba0080-533b-11ea-87e2-8e48edeaa318.png)

**Comment by alanmur** [comment]
Unexpected. Try this one instead. I migrated packages.config to PackageReference. Not sure why your VS2017 couldn't read it.
[ReproAuthFail.zip](https://github.com/aws-samples/amazon-gamelift-unity/files/4227683/ReproAuthFail.zip)

**Comment by xavinux** [comment]
This is what I get after building and running the unzip file in VS 2017:

**Hello World!
Profile: demo-gamelift-unity
CP1
CP2
CP3
CP4
CP5
demo-gamelift-unity profile
Goodbye**

Best Regards.

**Comment by alanmur** [comment]
OK it didn't throw an exception. That's different from the game itself. I need to think about this a bit more to work out why it threw in Unity, but the test case didn't throw, which is the same code.

**Comment by xavinux** [comment]
No problem. Let me know if there Is something else I can help with testing. 

Regards.

**Comment by alanmur** [comment]
Hello!

Sorry for the delay. I have made some modifications to the way that credentials are handled in the project. Please go to [https://github.com/aws-samples/amazon-gamelift-unity/tree/credfix](https://github.com/aws-samples/amazon-gamelift-unity/tree/credfix) and there you will find a branch (credfix) that I believe will fix your problem. How to use:

Get the credfix branch, which will change three files. Note that the standalone player log may have moved location.

Build the client as discussed in the instructions.

Run the client with rc --credentials <file> to load the credentials.

Attach the Player.log file for me to look at. Also it should work for you! Let me know, and if we are good I will merge the changes.

**Comment by xavinux** [comment]
Hello!

Will test this and see if it works.

Thank you very much for your help.

Best Regards,

**Comment by alanmur** [comment]
Just wondering if you had a chance to test?

**Comment by xavinux** [comment]
sorry, not yet
